import os
import google.generativeai as genai
from datetime import datetime
import pytz
import time  # 引入時間模組，用於控制速度

# 設定 API Key
genai.configure(api_key=os.environ["GEMINI_API_KEY"])

# --- 使用性能更強的 Pro 模型 ---
model = genai.GenerativeModel('gemini-pro')

# 取得台灣時間
tw_time = datetime.now(pytz.timezone('Asia/Taipei')).strftime("%Y-%m-%d %H:%M")

# --- 您的關注清單 ---
prompts = [
    {
        "title": "🚀 LUNR (Intuitive Machines) 動態",
        "query": "請詳細分析美股代碼 LUNR (Intuitive Machines) 的最新股價技術面、近期合約進展、重要新聞以及社群論壇（如 Reddit, X）的討論熱度與情緒。"
    },
    {
        "title": "🌌 FLY (Firefly Aerospace) 追蹤",
        "query": "請深入挖掘 Firefly Aerospace (FLY) 的最新動態，包含上市進度、供應鏈消息、合作夥伴以及任何潛在的政府合約新聞。"
    },
    {
        "title": "💰 黃金與宏觀經濟 (Golden Window)",
        "query": "請分析當前的宏觀經濟數據（通膨、利率），並結合「金穹 (Golden Window)」理論，解讀黃金價格走勢與美國三大戰略計劃（金穹、Janus、Artemis）的關聯性。"
    },
    {
        "title": "⚛️ 核能板塊深度掃描",
        "query": "請針對美股核能板塊重點個股：OKLO, BWXT, SMR, LEU 進行綜合分析。請比較它們近期的消息面利多與利空，並評估短期內的投資風險與機會。"
    },
    {
        "title": "🇹🇼 台積電 (2330/TSM) 戰略分析",
        "query": "請整理台積電 (2330/TSM) 最新的法說會關鍵數據、高層對未來的展望言論，以及華爾街與外資機構對其後市的最新評級與目標價調整。"
    }
]

# --- 生成 HTML 內容 ---
html_content = f"""
<!DOCTYPE html>
<html lang="zh-TW">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>個人美股戰情室 ({tw_time})</title>
    <style>
        body {{ font-family: "Microsoft JhengHei", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.8; max-width: 900px; margin: 0 auto; padding: 20px; background-color: #f0f2f5; color: #1c1e21; }}
        h1 {{ text-align: center; color: #003366; border-bottom: 3px solid #d32f2f; padding-bottom: 15px; margin-bottom: 10px; }}
        .timestamp {{ text-align: center; color: #606770; font-size: 0.9em; margin-bottom: 40px; }}
        .card {{ background: white; padding: 30px; margin-bottom: 25px; border-radius: 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.08); }}
        h2 {{ color: #d32f2f; margin-top: 0; border-left: 5px solid #003366; padding-left: 10px; }}
        strong {{ color: #000; font-weight: 700; background-color: #fff3cd; padding: 0 4px; }}
        li {{ margin-bottom: 8px; }}
        .error {{ color: red; background: #ffe6e6; padding: 10px; border-radius: 5px; }}
    </style>
</head>
<body>
    <h1>📈 個人美股戰情室 (Pro 深度版)</h1>
    <p class="timestamp">更新時間：{tw_time} (UTC+8)</p>
"""

print("🚀 開始生成 Pro 版深度報告...")

for index, item in enumerate(prompts):
    print(f"[{index+1}/{len(prompts)}] 正在深度分析：{item['title']}...")
    try:
        response = model.generate_content(item['query'])
        
        # 將 Markdown 格式轉為 HTML
        text_content = response.text
        text_content = text_content.replace("### ", "<h3>").replace("###", "</h3>")
        text_content = text_content.replace("**", "<strong>").replace("* ", "<li>").replace("\n", "<br>")
        
        html_content += f"""
        <div class="card">
            <h2>{item['title']}</h2>
            <div>{text_content}</div>
        </div>
        """
        print("   ✅ 分析完成")
        
    except Exception as e:
        print(f"   ❌ 發生錯誤：{str(e)}")
        html_content += f"<div class='card'><h2>{item['title']}</h2><p class='error'>分析失敗，原因：{str(e)}</p></div>"

    # --- 安全防護：每跑完一個請求，休息 35 秒 ---
    if index < len(prompts) - 1:
        print("⏳ 為確保 Pro 模型連線穩定，系統冷卻 35 秒...")
        time.sleep(35)

html_content += """
    <footer style="text-align: center; margin-top: 50px; padding-top: 20px; border-top: 1px solid #ddd; color: #777; font-size: 0.8em;">
        Generated by Google Gemini 1.5 Pro | Automated via GitHub Actions
    </footer>
</body>
</html>
"""

# 寫入 index.html
with open("index.html", "w", encoding="utf-8") as f:
    f.write(html_content)

print("🎉 報告全部生成完畢！")
